# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BuildingChangeToCAD
                                 A QGIS plugin
 Automated building change detection from satellite imagery to CAD layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-14
        copyright            : (C) 2026 by Abdalrhman Musa
        email                : hatmm2749@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BuildingChangeToCAD class from file BuildingChangeToCAD.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .building_change_to_cad import BuildingChangeToCAD
    return BuildingChangeToCAD(iface)
